homeassistant:
  customize:
    sensor.system_magic_mirror_rpi:
      icon: mdi:raspberrypi
    sensor.system_dashboard_rpi:
      icon: mdi:raspberrypi
    sensor.system_hass_rpi:
      icon: mdi:home-assistant
    sensor.system_rpi_zero:
      icon: mdi:raspberrypi
    sensor.system_stefan_computer:
      icon: mdi:monitor
    sensor.system_isa_laptop:
      icon: mdi:laptop-windows
    sensor.system_isa_computer:
      icon: mdi:monitor
    sensor.system_asus_router:
      icon: mdi:wifi
    sensor.system_netgear_router:
      icon: mdi:wifi
    sensor.system_printer:
      icon: mdi:printer
    sensor.system_nas:
      icon: mdi:server
    sensor.system_chromecast_bedroom:
      icon: mdi:cast
    sensor.system_shield:
      icon: mdi:android
    # sensor.system_shield_2:
    #   icon: mdi:android
    sensor.system_ipad:
      icon: mdi:tablet-ipad
    sensor.system_movie_system:
      icon: mdi:speaker
    sensor.system_samsung65:
      icon: mdi:television
    # sensor.system_hue_hub:
      # icon: mdi:lightbulb-outline
    sensor.system_ikea_gateway:
      icon: mdi:google-keep
    sensor.system_xiaomi_gateway:
      icon: mdi:circle-outline
    sensor.system_ip_camera:
      icon: mdi:webcam
    sensor.system_galaxy_tab:
      icon: mdi:tablet-android
    sensor.system_samsung49:
      icon: mdi:television
    sensor.system_ir_blaster:
      icon: mdi:remote
    sensor.system_ir_blaster_bedroom:
      icon: mdi:remote
    sensor.system_ir_blaster_living_room:
      icon: mdi:remote
    sensor.system_withings_scale:
      icon: mdi:scale-bathroom
    sensor.system_sonos_3:
      icon: mdi:speaker
    sensor.system_milight_hub:
      icon: mdi:google-keep
    sensor.system_ring_doorbell:
      icon: mdi:doorbell-video
    sensor.system_ring_chime_pro:
      icon: mdi:wifi
    sensor.system_ring_chime:
      icon: mdi:bell-outline
    sensor.system_isa_dell_xps:
      icon: mdi:laptop-windows
    sensor.system_stefan_laptop:
      icon: mdi:laptop-windows

  customize_glob:
    sensor.system_*:
      templates:
        hs_color: "if (state === 'Online') return [0, 0];
        else if (state === 'Unknown') return [40, 70];
        else if (state === 'Offline') return [0, 85];"    
      
sensor:
  - platform: template
    sensors:
        system_milight_hub:
          friendly_name: 'Milight Hub'
          entity_id: "device_tracker.milight_controller"
          value_template: "{{ 'Online' if is_state('device_tracker.milight_controller', 'home') else 'Offline' }}"
        system_nas:
          friendly_name: 'Synology NAS'
          entity_id: "device_tracker.synology_nas"
          value_template: "{{ 'Online' if is_state('device_tracker.synology_nas', 'home') else 'Offline' }}"
        system_samsung65:
          friendly_name: 'Living Room TV'
          entity_id: "device_tracker.living_room_tv"
          value_template: "{{ 'Online' if is_state('device_tracker.living_room_tv', 'home') else 'Offline' }}"
        system_samsung49:
          friendly_name: 'Bedroom TV'
          entity_id: "device_tracker.bedroom_tv"
          value_template: "{{ 'Online' if is_state('device_tracker.bedroom_tv', 'home') else 'Offline' }}"
        system_movie_system:
          friendly_name: 'Living Room Movie System'
          entity_id: "device_tracker.living_room_movie_system"
          value_template: "{{ 'Online' if is_state('device_tracker.living_room_movie_system', 'home') else 'Offline' }}"
        system_netgear_router:
          friendly_name: 'Netgear Router'
          entity_id: "device_tracker.netgear_router"
          value_template: "{{ 'Online' if is_state('device_tracker.netgear_router', 'home') else 'Offline' }}"
        system_shield:
          friendly_name: 'NVidia Shield'
          entity_id: "device_tracker.nvidia_shield"
          value_template: "{{ 'Online' if is_state('device_tracker.nvidia_shield', 'home') else 'Offline' }}"
        # system_shield_2:
        #   friendly_name: 'NVidia Shield 2'
        #   entity_id: "device_tracker.shield"
        #   value_template: "{{ 'Online' if is_state('device_tracker.shield', 'home') else 'Offline' }}"
        system_chromecast_bedroom:
          friendly_name: 'Chromecast Bedroom'
          entity_id: "device_tracker.chromecast_bedroom"
          value_template: "{{ 'Online' if is_state('device_tracker.chromecast_bedroom', 'home') else 'Offline' }}"
        system_stefan_computer:
          friendly_name: 'Stefan computer'
          entity_id: "device_tracker.stefan_computer"
          value_template: "{{ 'Online' if is_state('device_tracker.stefan_computer', 'home') else 'Offline' }}"
        system_stefan_laptop:
          friendly_name: 'Stefan laptop'
          entity_id: "device_tracker.cnstefang"
          value_template: "{{ 'Online' if is_state('device_tracker.cnstefang', 'home') else 'Offline' }}"
        system_isa_computer:
          friendly_name: 'Isas computer'
          entity_id: "device_tracker.isa_computer"
          value_template: "{{ 'Online' if is_state('device_tracker.isa_computer', 'home') else 'Offline' }}"
        system_isa_laptop:
          friendly_name: 'Isas old laptop'
          entity_id: "device_tracker.isa_laptop"
          value_template: "{{ 'Online' if is_state('device_tracker.isa_laptop', 'home') else 'Offline' }}"
        system_isa_dell_xps:
          friendly_name: 'Isa Dell XPS'
          entity_id: "device_tracker.desktop39i618g"
          value_template: "{{ 'Online' if is_state('device_tracker.desktop39i618g', 'home') else 'Offline' }}"        
        system_printer:
          friendly_name: 'HP Printer'
          entity_id: "device_tracker.hp_printer"
          value_template: "{{ 'Online' if is_state('device_tracker.hp_printer', 'home') else 'Offline' }}"
        system_ipad:
          friendly_name: 'iPad'
          entity_id: "device_tracker.paddan"
          value_template: "{{ 'Online' if is_state('device_tracker.paddan', 'home') else 'Offline' }}"
        # system_galaxy_tab:
        #   friendly_name: 'Galaxy Tab'
        #   entity_id: "device_tracker.android8c0fc07d9694a5a2"
        #   value_template: "{{ 'Online' if is_state('device_tracker.android8c0fc07d9694a5a2', 'home') else 'Offline' }}"
        # system_hue_hub:
        #   friendly_name: 'Philips Hue Gateway'
        #   entity_id: "device_tracker."
        #   value_template: "{{ 'Online' if is_state('device_tracker.philipshue', 'home') else 'Offline' }}"
        system_asus_router:
          friendly_name: 'Asus Router'
          entity_id: "device_tracker.router_asus"
          value_template: "{{ 'Online' if is_state('device_tracker.router_asus', 'home') else 'Offline' }}"
        system_ip_camera:
          friendly_name: 'Sannce Camera'
          entity_id: "device_tracker.sannce_ip_camera"
          value_template: "{{ 'Online' if is_state('device_tracker.sannce_ip_camera', 'home') else 'Offline' }}"
        system_ir_blaster:
          friendly_name: 'Broadlink IR Blaster Hallway'
          entity_id: "device_tracker.broadlink_hallway"
          value_template: "{{ 'Online' if is_state('device_tracker.broadlink_hallway', 'home') else 'Offline' }}"
        system_withings_scale:
          friendly_name: 'Withings scale'
          entity_id: "device_tracker.0024e40a2868"
          value_template: "{{ 'Online' if is_state('device_tracker.0024e40a2868', 'home') else 'Offline' }}"
        system_ir_blaster_bedroom:
          friendly_name: 'Broadlink IR Blaster Bedroom'
          entity_id: "device_tracker.broadlink_bedroom"
          value_template: "{{ 'Online' if is_state('device_tracker.broadlink_bedroom', 'home') else 'Offline' }}"
        system_ir_blaster_living_room:
          friendly_name: 'Broadlink IR Blaster Living Room'
          entity_id: "device_tracker.broadlink_rmminiccec6f"
          value_template: "{{ 'Online' if is_state('device_tracker.broadlink_rmminiccec6f', 'home') else 'Offline' }}"
        # system_ikea_gateway:
        #   friendly_name: 'Ikea Trådfri Gateway'
        #   entity_id: "device_tracker."
        #   value_template: "{{ 'Online' if is_state('device_tracker.tradfri_gateway', 'home') else 'Offline' }}"
        system_xiaomi_gateway:
          friendly_name: 'Xiaomi Gateway'
          entity_id: "device_tracker.xiaomi_gateway"
          value_template: "{{ 'Online' if is_state('device_tracker.xiaomi_gateway', 'home') else 'Offline' }}"
        system_sonos:
          friendly_name: 'Sonos'
          entity_id: "device_tracker.sonos_play_3"
          value_template: "{{ 'Online' if is_state('device_tracker.sonos_play_3', 'home') else 'Offline' }}"
        system_magic_mirror_rpi:
          friendly_name: 'Dashboard RPi'
          entity_id: "device_tracker.raspberrypi_3"
          value_template: "{{ 'Online' if is_state('device_tracker.raspberrypi_3', 'home') else 'Offline' }}"
        system_hass_rpi:
          friendly_name: 'Hass RPi'
          entity_id: "device_tracker.raspberrypi"
          value_template: "{{ 'Online' if is_state('device_tracker.raspberrypi', 'home') else 'Offline' }}"
        system_dashboard_rpi:
          friendly_name: '7" Dashboard RPi'
          entity_id: "device_tracker.raspberrypi_2"
          value_template: "{{ 'Online' if is_state('device_tracker.raspberrypi_2', 'home') else 'Offline' }}"
        system_rpi_zero:
          friendly_name: 'RPi Zero'
          entity_id: "device_tracker.raspberrypi_4"
          value_template: "{{ 'Online' if is_state('device_tracker.raspberrypi_4', 'home') else 'Offline' }}"
        system_ring_doorbell:
          friendly_name: 'Ring'
          entity_id: "device_tracker.ring"
          value_template: "{{ 'Online' if is_state('device_tracker.ring', 'home') else 'Offline' }}"
        system_ring_chime_pro:
          friendly_name: 'Ring Chime Pro'
          entity_id: "device_tracker.chimepro93_2"
          value_template: "{{ 'Online' if is_state('device_tracker.chimepro93_2', 'home') else 'Offline' }}"
        system_ring_chime:
          friendly_name: 'Ring Chime'
          entity_id: "device_tracker.3ca3087ee76e"
          value_template: "{{ 'Online' if is_state('device_tracker.3ca3087ee76e', 'home') else 'Offline' }}"
        system_dafang:
          friendly_name: 'Dafang'
          entity_id: "device_tracker.7811dc70faaf"
          value_template: "{{ 'Online' if is_state('device_tracker.7811dc70faaf', 'home') else 'Offline' }}"
        system_axis_living_room:
          friendly_name: 'Axis Living Room'
          entity_id: "device_tracker.axis_00408cd5badd"
          value_template: "{{ 'Online' if is_state('device_tracker.axis_00408cd5badd', 'home') else 'Offline' }}"
        system_axis_passage:
          friendly_name: 'Axis Passage'
          entity_id: "device_tracker.axis_00408cd5bad6"
          value_template: "{{ 'Online' if is_state('device_tracker.axis_00408cd5bad6', 'home') else 'Offline' }}"
automation:
  - alias: '[System] Device Status'
    initial_state: 'on'
    trigger:
         - platform: state
           entity_id:
              - sensor.system_asus_router
              - sensor.system_netgear_router
              - sensor.system_printer
              - sensor.system_nas
              # - sensor.system_hue_hub
              - sensor.system_ir_blaster
              - sensor.system_ir_blaster_bedroom
              - sensor.system_ip_camera
            #  - sensor.system_ir_blaster_living_room
              - sensor.system_xiaomi_gateway
              - sensor.system_milight_hub
              - sensor.system_ring_doorbell
              - sensor.system_ring_chime_pro
              - sensor.system_ring_chime
              - sensor.system_axis_living_room
              - sensor.system_dafang
              - sensor.system_ip_camera
              
           to: 'Offline'
           for:
             minutes: 5
    action:
      - service: notify.ios_isabellas_iphone_x
        data_template:
          title: 'Device {{ trigger.to_state.name }} is'
          message: >
            '{{ trigger.to_state.state }}'